### ISSUE TITLE
entity with required pattern generated error in test javascript and stop to contnue import-jdl.

### ISSUE THREAD

**Issue by AlvinSanusi** [jhipster/react-jhipster#53]
An entity with email field:
emailaddr String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)

generate error in the test javascript as below:

  force src\test\javascript\e2e\entities\cln-client\cln-client.page-object.ts
SyntaxError: Invalid character. (96:78)
  94 |         expect(await clnClientUpdatePage.getWebsiteInput()).to.match(/website/);
  95 |         await clnClientUpdatePage.setEmailtoInput('\(@/w.x#ZU');
> 96 |         expect(await clnClientUpdatePage.getEmailtoInput()).to.match(/\(@/w.x#ZU/);
     |                                                                              ^
  97 |         await clnClientUpdatePage.setEmailcc1Input('emailcc1');
  98 |         expect(await clnClientUpdatePage.getEmailcc1Input()).to.match(/emailcc1/);
  99 |         await clnClientUpdatePage.setEmailcc2Input('emailcc2');
    at t (C:\Projects\RiskManage\RiskManage\node_modules\prettier\parser-typescript.js:1:285)
    at Object.parse (C:\Projects\RiskManage\RiskManage\node_modules\prettier\parser-typescript.js:14:180461)
    at Object.parse (C:\Projects\RiskManage\RiskManage\node_modules\prettier\index.js:9739:19)
    at coreFormat (C:\Projects\RiskManage\RiskManage\node_modules\prettier\index.js:13252:23)
    at format (C:\Projects\RiskManage\RiskManage\node_modules\prettier\index.js:13510:73)
    at formatWithCursor (C:\Projects\RiskManage\RiskManage\node_modules\prettier\index.js:13526:12)
    at C:\Projects\RiskManage\RiskManage\node_modules\prettier\index.js:44207:15
    at Object.format (C:\Projects\RiskManage\RiskManage\node_modules\prettier\index.js:44226:12)
    at C:\Projects\RiskManage\RiskManage\node_modules\generator-jhipster\generators\generator-transforms.js:44:39

**Comment by pascalgrimaud** [comment]
plz fill the template, using `jhipster info`

**Comment by AlvinSanusi** [comment]
Thanks pascalgrimaud,
Unfortunately, I can not figure out how to fill the template, using jhipster info.
Can you provide a little bit guide.
I am really sorry I don't know what you meant by using jhipster info.

**Comment by pascalgrimaud** [comment]
In your JHipster project folder, just type `jhipster info`, and it will display all information related to your project, so we can try to reproduce the issue.

Unless you use this library separately inside your own project (without JHipster) ?

**Comment by AlvinSanusi** [comment]
Please close this log because after I use different version of jhipster, it is working properly now.
